# Generated by Django 4.1.7 on 2023-05-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='supportsystemuser',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
