version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
      - celery-worker
  db:
    image: postgres:12.0-alpine
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: ''
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    command: celery -A SupportAPI worker --loglevel=info

volumes:
  postgres_data: